name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: build jar package
    - run: mvn -B package --file pom.xml
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag java-api:$(date +%s)
      
    - name: Publish Docker image
    - run: docker push ghcr.io/kotylu/java-api:latest
